const IMAGES = {
    craftingImage: require('../assets/CraftingImage.png'),
    startUpNewsImage: require('../assets/StartUpNewsImage.png'),
    nuStartzLogo: require('../assets/NuStartzLogo.png'),
    constructionCrane: require('../assets/Construction-Crane.png'),
    company: require('../assets/Company.png'),
    port: require('../assets/Port.png'),
    testimonialImage: require('../assets/Testimonial-Image.png'),
    mynaLogo: require('../assets/Myna-Logo.png'),
    beyondMediaLogo: require('../assets/BeyondMedia-Logo.png'),
    teledoctorLogo: require('../assets/TeleDoctor-Logo.png'),
    glgLogo: require('../assets/GLG-Logo.png'),
    microsoftLogo: require('../assets/Microsoft-Partner.png'),
    snapLogicLogo: require('../assets/SnapLogic-Partner.png'),
    koreAILogo: require('../assets/KoreAI-Partner.png'),
    linkedIn: require('../assets/LinkedIn.png'),
    twitter: require('../assets/Twitter.png'),
    facebook: require('../assets/Facebook.png'),
    youtube: require('../assets/Youtube.png'),
    creativity: require('../assets/Creativity.png'),
    strength: require('../assets/Strength.png'),
    progress: require('../assets/Progress.png'),
    serviceImage: require('../assets/ServiceHeroImage.png'),
    serviceIcon: require('../assets/ServiceIcon.png'),
    techStartupImage1: require('../assets/TechStartupImage1.png'),
    techStartupImage2: require('../assets/TechStartupImage2.png'),
    homeHeroSectionBackground: require('../assets/HomeHeroSectionBackground2.png'),
    serviceHeroSectionBackground: require('../assets/ServiceHeroSectionBackground.png'),
    operateTextImage: require('../assets/OperateText.png'),
    buildTextImage: require('../assets/BuildText.png'),
    transferTextImage: require('../assets/TransferText.png'),
    eventImage1: require('../assets/Event1.png'),
    eventImage2: require('../assets/Event2.png'),
    eventImage3: require('../assets/Event3.png'),
}


export default IMAGES